"""update city

Revision ID: 22e0c2b54ff2
Revises: f14257fb4e62
Create Date: 2023-04-27 21:20:51.827504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e0c2b54ff2'
down_revision = 'f14257fb4e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('city')

    # ### end Alembic commands ###
